out.txt: main.exe
	mono $< > $@

main.exe: main.cs vector.dll matrix.dll mini.dll
	mcs $< -target:exe -reference:matrix.dll  -reference:vector.dll -reference:mini.dll

mini.dll: mini.cs matrix.dll vector.dll
	mcs $< -target:library -reference:vector.dll -reference:matrix.dll

matrix.dll: ../../linearequations/A/matrix.cs vector.dll
	mcs -out:./$@ $(filter %.cs,$^) -target:library -reference:vector.dll

vector.dll: ../../linearequations/A/vector.cs
	mcs -out:./$@ $(filter %.cs,$^) -target:library


PHONEY: clean
clean:
	rm -f *.txt *.exe
